sudo: false
cache: bundler
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-9.0.1.0
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
  fast_finish: true
install:
  - bundle install --retry=3
script:
  - bundle exec rspec
